version: 1.0.{build}
branches:
  only:
  - main
image: Visual Studio 2022
environment:
  NPM_TOKEN:
    secure: Ifg1yAousKDCEOYdzweSr2HxPZBNcbDU79zUEKxgtSZcjzmcdJXK66skqU4xa9D+
build_script:
- ps: >-
    .\build_npm.ps1