version: 1.0.{build}
branches:
  only:
  - main
image: Visual Studio 2022
environment:
  NPM_TOKEN:
    secure: +tsLqJ9V4Q9Df0x1pA6L4uJ514x9QKgIrg5GuDInrC/KErJoTNyQ/ZNiaadWG3Q8
build_script:
- ps: >-
    .\build_npm.ps1